### ISSUE TITLE
Frontend uploads are not inside the Contao root dir

### ISSUE THREAD

**Issue by rabauss** [numero2/contao-proper-filenames#10]
Unfortunately, for us the uploads in the frontend are not working properly anymore, because files are uploaded to a temporary folder which is not inside the contao root. Because of that the following line will throw an error `"/tmp/phpAbc" is not inside the Contao root dir "xyz/contao"`

https://github.com/numero2/contao-proper-filenames/blob/ee2812a521eeea7ce416a4e9f9ef53ea62671709/src/Resources/contao/classes/CheckFilenames.php#L104

Has anyone else the same problems or is there a solution to disable the proper filenames for the frontend forms?

**Comment by rabauss** [comment]
Oh I see there was a related but closed issue https://github.com/numero2/contao-proper-filenames/issues/9
We also use the core upload in a form from the generator!

**Comment by bennyborn** [comment]
Thanks @rabauss 🎉

I just made a new release that catches the exception and also adds a checkbox to the backend to prevent certain upload fields from being sanitized at all (if needed).

![image](https://user-images.githubusercontent.com/226890/136179294-d43de176-bda1-4c59-af75-e95cf9bc2f5e.png)
