### ISSUE TITLE
Auto-renaming of duplicate file names does not work when filename is sanitized

### ISSUE THREAD

**Issue by fritzmg** [numero2/contao-proper-filenames#13]
If you enable the options _Store uploaded files_ and _Preserve existing files_ (and do not disable _Do not check/rename uploaded files_) and then upload a file with illegal characters in its name (which are then sanitised) twice or more, the uploaded files do not get automatically renamed anymore.

**Comment by bennyborn** [comment]
Ah okay, got it.

Hmm it seems like we'd need to take care of `doNotOverwrite` ourself.

**Comment by fritzmg** [comment]
> Hmm it seems like we'd need to take care of `doNotOverwrite` ourself.

Hm, may be you could also usethe `loadFormField` hook instead. In there you could check additionally for

```php
if (Input::post('FORM_SUBMIT') == $formId) {
    return $objWidget;
}
```

And then you would manipulate `$_FILES[$objWidget->name]` instead of `$_SESSION['FILES'][$objWidget->name]`. Then afterwards `FormFileUpload::validate` would work as usual and take care of everything.

**Comment by bennyborn** [comment]
> Hm, may be you could also use the `loadFormField` hook instead.

Ah, love the "out of the box thinking"! Seems to work even better and saves us so much trouble :)
