### ISSUE TITLE
Only two uploads if doNotTrimFilenames is deactivated

### ISSUE THREAD

**Issue by akroii** [numero2/contao-proper-filenames#14]
Greetings,
when i uncheck the chexbox `doNotTrimFilenames `only two uploads where uploaded.

I have 13 pdf files, which i upload simultaneously.
All files look like this:
```
NiNu_Lokales_MA_Poster_Update_2051_KV_Nordrhein_v06.pdf
NiNu_Lokales_MA_Poster_Update_2051_KV_Mecklenburg-Vorpommern_v06.pdf
```

The upload runs completely, but after it only remains 2 files.

Contao 4.9.22
numero2/contao-proper-filenames 2.1.4

**Comment by bennyborn** [comment]
If all the files have a filename that starts the same and have around the same length I can totally see why having `doNotTrimFilenames` unchecked could cause this. That is not a bug, rather expected behaviour 🤷‍♂️ 

Take a look at how the files are named after uploading.

**Comment by akroii** [comment]
My files are in lowercase after uploading
![image](https://user-images.githubusercontent.com/8830861/139849080-2a9597f1-c03a-406c-b42c-8f352b2dfdb5.png)

**Comment by bennyborn** [comment]
What is the actual name of the file after uploading?

**Comment by akroii** [comment]
Before:
`NiNu_Lokales_MA_Poster_2021_KV_Berlin.pdf`
After:
`ninu_lokales_ma_poster_2021_kv_b`

**Comment by bennyborn** [comment]
You see? If you were now to upload a file named `NiNu_Lokales_MA_Poster_2021_KV_Bremen.pdf` it would be truncated to the same name and therefore overwrite the old file. So in your case you should enable `doNotTrimFilenames` globally or at least enable `Do not check/rename` for the folder in the File Manager.

**Comment by akroii** [comment]
and why only 2 files being uploaded?

**Comment by fritzmg** [comment]
Post all file names, that you are trying to upload.

**Comment by bennyborn** [comment]
Can't tell. My best bet is that rather than there being a problem with the upload itself (which we don't intercept) it might come down to files being renamed to the same filename and therefor overwritten.

**Comment by akroii** [comment]
```
NiNu_Lokales_MA_Poster_2021_KV_Berlin.pdf
NiNu_Lokales_MA_Poster_Update_2051_KV_Baden-Wuertemberg_v06.pdf
NiNu_Lokales_MA_Poster_Update_2051_KV_Brandenburg_v06.pdf
NiNu_Lokales_MA_Poster_Update_2051_KV_Hamburg_v06.pdf
NiNu_Lokales_MA_Poster_Update_2051_KV_Mecklenburg-Vorpommern_v06.pdf
NiNu_Lokales_MA_Poster_Update_2051_KV_Niedersachsen_v06.pdf
NiNu_Lokales_MA_Poster_Update_2051_KV_Nordrhein_v06.pdf
NiNu_Lokales_MA_Poster_Update_2051_KV_Rheinland-Pfalz,v06.pdf
NiNu_Lokales_MA_Poster_Update_2051_KV_Saarland_v06.pdf
NiNu_Lokales_MA_Poster_Update_2051_KV_Sachsen_v06.pdf
NiNu_Lokales_MA_Poster_Update_2051_KV_Schleswig-Holstein_v06.pdf
NiNu_Lokales_MA_Poster_Update_2051_KV_Thueringen_v06.pdf
NiNu_Lokales_MA_Poster_Update_2051_KV_Westfalen-Lippe_v06.pdf

```

**Comment by bennyborn** [comment]
`NiNu_Lokales_MA_Poster_2021_KV_Berlin.pdf` becomes `ninu_lokales_ma_poster_2021_kv_b.pdf` and therefore all your other files will be renamed to `ninu_lokales_ma_poster_update_20.pdf`

**Comment by fritzmg** [comment]
@akroii if you need file names that are longer than 32 characters, then you need to disable the functionality to automatically shorten file names to 32 characters.

**Comment by akroii** [comment]
@fritzmg of course, i already did. 

it becomes duplicates. this is why only two files remaining. 🤦‍♂️
