### ISSUE TITLE
Fehler 4 beim Hochladen der Datei .! 

### ISSUE THREAD

**Issue by Acta2000** [numero2/contao-proper-filenames#15]
Contao 4.9.25

Ich habe ein Formular mit 3 Upload-Feldern. Die Dateien werden auf dem Server gespeichert.

Sofern alle Upload-Felder mit Dateien bestückt werden, läuft das Formular ohne Probleme durch.

Wird jedoch keine Datei ausgewählt, erhalte ich beim Absenden immer die Meldung "Fehler 4 beim Hochladen der Datei .!."

Im Debug Modus: Bekomme ich beim Absenden nur eine 200 angezeigt.
Laut Debug_Modus werden für die Drei Uploadfelder folgende werte übergeben:

` Uploaded Files
Key 	Value
Upload 	

null

Upload2 	

null

Upload3 	

null `

Wenn ich die Erweiterung aus Contao entferne, funktioniert das Formular wie gedacht.

**Comment by bennyborn** [comment]
Besten Dank, gefixt in `v2.1.5`!
