### ISSUE TITLE
Dateiverwaltung - Neuer Ordner

### ISSUE THREAD

**Issue by operatorone** [numero2/contao-proper-filenames#19]
Beim Erstellen eines neuen Ordners erhalte ich im Backen einen 500er Fehler und im Log findet sich folgende Meldung:

`[2022-07-26T14:41:56.394249+02:00] request.CRITICAL: Uncaught PHP Exception TypeError: "numero2\ProperFilenamesBundle\EventListener\DataContainer\FilesListener::checkParentFolder(): Return value must be of type string, null returned" at /var/www/clients/client150/web878/web/contao_live/vendor/numero2/contao-proper-filenames/src/EventListener/DataContainer/FilesListener.php line 108 {"exception":"[object] (TypeError(code: 0): numero2\\ProperFilenamesBundle\\EventListener\\DataContainer\\FilesListener::checkParentFolder(): Return value must be of type string, null returned at /var/www/clients/client150/web878/web/contao_live/vendor/numero2/contao-proper-filenames/src/EventListener/DataContainer/FilesListener.php:108)"} []`

Contao 4.13.6
PHP 8.1

**Comment by bennyborn** [comment]
Willst Du mal den DEV-Master ausprobieren? Wir haben letzte Woche Updates für Contao 5 / PHP 8.1 gemacht. Sollte dort nicht mehr auftauchen.

**Comment by operatorone** [comment]
Klar, kann ich gerne machen 🙂

**Comment by operatorone** [comment]
Hab den DEV-Master installiert. Leider wieder folgende Meldung:
`[2022-07-26T15:00:19.218129+02:00] request.CRITICAL: Uncaught PHP Exception TypeError: "numero2\ProperFilenamesBundle\EventListener\DataContainer\FilesListener::checkParentFolder(): Return value must be of type string, null returned" at /var/www/clients/client150/web878/web/contao_live/vendor/numero2/contao-proper-filenames/src/EventListener/DataContainer/FilesListener.php line 108 {"exception":"[object] (TypeError(code: 0): numero2\\ProperFilenamesBundle\\EventListener\\DataContainer\\FilesListener::checkParentFolder(): Return value must be of type string, null returned at /var/www/clients/client150/web878/web/contao_live/vendor/numero2/contao-proper-filenames/src/EventListener/DataContainer/FilesListener.php:108)"} []
`

**Comment by bennyborn** [comment]
Ist nun im aktuellen Commit gefixt 😊
