### ISSUE TITLE
Contao 4.8.5: Not working

### ISSUE THREAD

**Issue by mimamuxx** [numero2/contao-proper-filenames#2]
Hi,
contao-proper-filenames isn't working under Contao 4.8.5.
Option checkbox under settings is not available.

**Comment by bennyborn** [comment]
I don't see why this should not work. We're attaching our fields to the `imageHeight` in `tl_settings` which is also present in 4.8.5. Are you sure there is no other extension causing that problem?

**Comment by mimamuxx** [comment]
me neither... I don't have any error in the logs...
Can't see any conflict warnings in the module information.
I use the Contao Manager 1.2.1

Extension List: 
- terminal42/contao-changelanguage 
- terminal42/contao-url-rewrite
- madeyourday/contao-rocksolid-theme-assistant
- madeyourday/contao-rocksolid-slider
- madeyourday/contao-rocksolid-icon-picker
- madeyourday/contao-rocksolid-custom-elements
- madeyourday/contao-rocksolid-columns
- dieschittigs/contao-recaptcha

Any idea?

**Comment by bennyborn** [comment]
Sure bet `dieschittigs/contao-recaptcha` is the problem. We already informed the guys about their problematic implementation in tl_settings but so far no response (see https://github.com/DieSchittigs/recaptcha-bundle/issues/10)

**Comment by mimamuxx** [comment]
thx. So I have to wait for @DieSchittigs ?

**Comment by bennyborn** [comment]
You could use some trickery to get around that for the moment.
Set your reCaptcha to V2, then our settings should be visible. Save em and switch back to V3 :)
