### ISSUE TITLE
Kompletten Dateibaum oder Teile davon umschreiben

### ISSUE THREAD

**Issue by zonky2** [numero2/contao-proper-filenames#20]
Es wäre schön, wenn man einen vorhandenen Dateibaum komplett "bereinigen" könnte - über einen Button in der Dateiverwaltung oder ein Command auf Konsole

**Comment by bennyborn** [comment]
Ja, die Idee hatten wir auch schon, allerdings muss man bei Bulk-Umbenennung echt aufpassen, da kann einiges schief gehen.

Man müsste sicherstellen das man den "Baum" quasi von Innen nach Außen umbenennt. Also erst auf der tiefsten Ebene die Dateien, dann die Ordner darüber usw.

Vielleicht kommt das Feature mal in Zukunft von uns aber ansonsten sind PR's auch immer willkommen 😊

**Comment by bennyborn** [comment]
Der Kollege @michb hatte etwas Zeit und sich darum gekümmert. Ist mit `v.2.2.0` nun mit rein gekommen 🥳
