### ISSUE TITLE
Umlaute umschreiben, statt entfernen

### ISSUE THREAD

**Issue by k-webdesign** [numero2/contao-proper-filenames#3]
Hi Benny,

Umlaute werden gelöscht, statt umgeschrieben zu werden. Gibts da eine Einstellung, die ich übersehen habe oder könnte das als neues Feature eingebaut werden?
![image001](https://user-images.githubusercontent.com/4130440/76143065-1f8c9080-6074-11ea-97b5-8839d5f1d2ac.png)

VG Kim

**Comment by bennyborn** [comment]
Hi Kim,
aktuell ist das Verhalten so gewollt da wir in 4.4 keine Core-Funktion mehr haben um die Aliase "sinnvoll umzuschreiben".  Da es aber bei späteren Versionen (glaube ab 4.7) den sog. Slug-Generator gibt hätten wir da wieder eine Möglichkeit. Ich packs mal mit auf den Zettel!
