### ISSUE TITLE
Umschreibung auf Frontend-Uploads erweitern?

### ISSUE THREAD

**Issue by FlorinvV** [numero2/contao-proper-filenames#5]
Hallo Benny,

wäre es möglich, das Umschreiben auch bei Upload-Feldern in Frontend-Formularen einzuführen?
Die Rate, dass jemand dort Dokumente hochlädt, die wegen Leer- und Sonderzeichen auf manche Arten nicht verarbeitet werden können, ist unglaublich hoch... '^^

Beste Grüße
Florin

**Comment by bennyborn** [comment]
Hi Florin,

finde ich grundlegend eine sehr gute Idee! :)
Jedoch sehe ich aktuell leider keine Möglichkeit wie wir uns dort reinhängen könnten.
Der Contao-Core gibt uns hier leider keine Hooks o.Ä. von daher befürchte ich das es noch etwas dauern könnte...
