### ISSUE TITLE
Unterstriche beibehalten

### ISSUE THREAD

**Issue by Catwatch** [numero2/contao-proper-filenames#7]
Ist es möglich die Unterstriche in einem Dateinamen beizubehalten?
Bisher werden diese auch durch Bindestriche ersetzt.

Gruß
André

**Comment by bennyborn** [comment]
Hi André, das sollte eigentlich auch so sein. 
Ich vermute das hat mit der letzten Änderung zu tun. Klappt es denn wenn Du die v2.0.4 nimmst?

**Comment by Catwatch** [comment]
Hi Benny,
habe auf die 2.04 ein Downgrade gemacht- Unterstriche funktionieren nun aber dafür werden die Umlaute ersatzlos gelöscht.

aus "über" wird "ber"

Gruß 
André

**Comment by bennyborn** [comment]
Ja, das war in der alten Version so. Dann müssen wir mal in der aktuellen schauen woran es liegt. Ich update das Issue sobald ich was weis :)

**Comment by Catwatch** [comment]
Moin Benny,
funktioniert!

Vielen Dank.

Gruß 
André
